### ISSUE TITLE
Error with running test-submission

### ISSUE THREAD

**Issue by sidthekidder** [drivendataorg/deid2-runtime#20]
**Environment**: AWS EC2 Deep Learning AMI (Ubuntu 18.04) Version 32.0, 

`make pull CPU_OR_GPU=cpu` and `make pack-benchmark` work fine but running `make test-submission` results in this error:

```
Running gpu image
Unpacking submission...
Archive:  ./submission/submission.zip
  inflating: ./main.py               
Running submission with Python

EnvironmentLocationNotFound: Not a conda environment: /home/appuser/miniconda/envs/py-gpu

Exporting submission.csv result...
ERROR: Script did not produce a submission.csv file in the main directory.

EnvironmentLocationNotFound: Not a conda environment: /home/appuser/miniconda/envs/py-gpu


EnvironmentLocationNotFound: Not a conda environment: /home/appuser/miniconda/envs/py-gpu

```

**Comment by r-b-g-b** [comment]
Hi @sidthekidder , I think you need to pass `CPU_OR_GPU=cpu` to `make test-submission`:

https://github.com/drivendataorg/deid2-runtime#quickstart

> On machines with nvidia-smi but a CUDA version other than 11, make will automatically select the GPU image, which will fail. In this case, you will have to set CPU_OR_GPU=cpu manually in the commands, e.g., make pull CPU_OR_GPU=cpu, make test-submission CPU_OR_GPU=cpu.

Let me know if that helps.
