### ISSUE TITLE
Can you add networkx to the python dependencies?

### ISSUE THREAD

**Issue by ryan112358** [drivendataorg/deid2-runtime#23]

**Comment by r-b-g-b** [comment]
Hi @ryan112358 ,

We encourage participants to make pull requests into this repo to add any additional dependencies to the runtime. See the [README](https://github.com/drivendataorg/deid2-runtime#2-updating-the-runtime-packages) for more instructions. You can also check out [this recent PR](https://github.com/drivendataorg/deid2-runtime/pull/22) as a good example of how it should go. As you can see, it doesn't require too many changes to the code. Let me know if you need any assistance!

**Comment by ryan112358** [comment]
Thanks @r-b-g-b , 

Looking at the README, I see I have to update py-cpu.yml file to add the dependency, but the format is a bit confusing to me.  For example, the last dependency is 

diffprivlib=0.3.0=pyh9f0ad1d_0

where does the pyh9f0ad1d_0 come from?

Also it takes upwards of an hour to build the docker image for some reason which is making it quite challenging for me to rapidly debug this, as I'm not familiar with docker.  Is it supposed to take that long?

**Comment by isms** [comment]
Closed by #24
